name: pixum-fotowereld
version: '0.1'
summary: |
  Fotoboek maken in topkwaliteit: het Pixum Fotoboek
description: |
  Gemakkelijk en snel jouw fotoboek maken in 9 verschillende formaten. Kies
  uit zes verschillende papiersoorten en meerdere soorten kaften en
  bindingen. Lees meer over onze verschillende fotoboek-formaten en
  opties of laat je inspireren door onze tips, workshops en klantenvoorbeelden!
  In een Pixum Fotoboek bundel je de mooiste momenten en herinneringen in topkwaliteit.

grade: devel
confinement: devmode
icon: snap/gui/pixum-fotowereld.png

plugs:
  gnome-3-26-1604:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-26-1604:gnome-3-26-1604


apps:
  pixum-fotowereld:
    command: desktop-launch env HOME="/home/$USER" $SNAP/Pixum\\ Fotowereld
    plugs:
      - x11
      - wayland
      - network-control
      - network-observe
      - firewall-control
      - home
      - gsettings
      - account-control
      - mount-observe
      - unity7
      - browser-support
      - desktop-legacy
      - desktop
      - network
      - process-control
      - system-observe
      - gnome-3-26-1604
parts:
  pixum-fotowereld:
    plugin: dump
    source: https://dls.photoprintit.com/api/getClient/12455-nl_BE/hps/f303030303030303030303030303030303030303030303030353635323936324/linux
    source-type: tar
    install: |
      echo `$SNAPCRAFT_PART_INSTALL/install.pl -k -i $SNAPCRAFT_PART_INSTALL <<EOF
      q
      ja
      EOF
      `
    after:
#      - desktop-qt5
#      - desktop-glib-only
      - desktop-gnome-platform
    stage-packages:
      - unzip
      - wget
      - libsnappy1v5
      - libxss1
#      - libglib2.0-bin
#      - libxtst6
